# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Genesys Impact
email: contact-us@genesysimpact.com
description: Creative engineers with a diverse background in design, development, mobile, and network technologies. Based in Washington DC
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://genesysimpact.com" # the base hostname & protocol for your site
twitter_username: genesysimpact
github_username:  genesysimpact

# Build settings
markdown: kramdown
